title: YCOde
description: This blog is my personal online journal mostly an outlet for technical, programming-related posts. It's my way to capture key ideas and concepts I find interesting in the software programming world.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
baseurl: "/YCOde"
